name: test tagging

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        type: text
        required: true

jobs:
  build:

    name: test
    runs-on: ubuntu-latest
    
    env:
      tag: ${{ github.event.inputs.tag || github.ref_name }}

    steps:
    - name: test ref_name
      run: echo $tag
      
    - name: Check file
      uses: andstor/file-existence-action@v1
      id: check_deb
      with:
        files: $tag
